- name: default
  run_list:
    - recipe[default]
  attributes:
    consul:
      version: 1.2.3
      config: &default-config
        owner: root
        ui: true
        bootstrap: true
        server: true
        datacenter: FortMeade
        encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
        acl_master_token: doublesecret
        acl_datacenter: FortMeade
        acl_default_policy: deny
  excludes:
    - windows-2012r2
    - windows-2016

- name: client
  run_list:
    - recipe[client_gem]
  excludes:
    - windows-2012r2
    - windows-2016

- name: git
  run_list:
      - recipe[default]
  attributes:
    go:
      version: 1.7
    consul:
      config: *default-config
      installation:
        provider: git
  excludes:
    - windows-2012r2
    - windows-2016

- name: windows
  run_list:
      - recipe[default]
  attributes:
    consul:
      version: 1.2.3
      config: &default-config
        log_file: "C:\\Progra~1\\Consul\\"
        log_rotate_bytes: 2_000_000
        log_rotate_duration: '3h'
        http_config:
          response_headers:
            Access-Control-Allow-Origin: '*'
  includes:
    - windows-2012r2
    - windows-2016

- name: windows_client
  run_list:
    - recipe[client_gem]
  includes:
    - windows-2012r2
    - windows-2016